stages:
  - build
  - test
  # - deploy

before_script:
  - yarn install

View Envs:
  image: node:10-alpine
  stage: build
  script: env | cut -d '=' -f 1

Linting:
  image: node:10-alpine
  stage: build
  script: yarn lint --max-warnings 1 # exit code will be non zero if there are any warnings

Production build:
  image: node:10-alpine
  stage: build
  script: yarn build

Security test:
  image: node:10-alpine
  stage: test
  script:
    - yarn add snyk
    - npx snyk test

Unit Test:
  image: node:10-alpine
  stage: test
  script: yarn test:unit

E2E Test:
  image: node:10-alpine
  stage: test
  script: yarn test:e2e
